-- Seeded lenders (generated from packages/shared/src/constants.ts)
INSERT INTO lenders (id, user_id, name, country, color, initial) VALUES
('seed-in-icici-bank', NULL, 'ICICI Bank', 'IN', '#B02A30', 'I'),
('seed-in-hdfc-bank', NULL, 'HDFC Bank', 'IN', '#004C8F', 'H'),
('seed-in-axis-bank', NULL, 'Axis Bank', 'IN', '#97144D', 'A'),
('seed-in-state-bank-of-india', NULL, 'State Bank of India', 'IN', '#22409A', 'S'),
('seed-in-kotak-mahindra-bank', NULL, 'Kotak Mahindra Bank', 'IN', '#ED1C24', 'K'),
('seed-in-idfc-first-bank', NULL, 'IDFC First Bank', 'IN', '#9C1D26', 'I'),
('seed-in-citi', NULL, 'Citi', 'IN', '#056DAE', 'C'),
('seed-in-hsbc', NULL, 'HSBC', 'IN', '#DB0011', 'H'),
('seed-in-standard-chartered', NULL, 'Standard Chartered', 'IN', '#0473EA', 'S'),
('seed-in-bajaj-finserv', NULL, 'Bajaj Finserv', 'IN', '#005DAC', 'B'),
('seed-in-yes-bank', NULL, 'Yes Bank', 'IN', '#00518F', 'Y'),
('seed-in-indusind-bank', NULL, 'IndusInd Bank', 'IN', '#8B1D41', 'I'),
('seed-in-bank-of-baroda', NULL, 'Bank of Baroda', 'IN', '#F26522', 'B'),
('seed-in-punjab-national-bank', NULL, 'Punjab National Bank', 'IN', '#A6192E', 'P'),
('seed-in-au-small-finance-bank', NULL, 'AU Small Finance Bank', 'IN', '#6D2077', 'A'),
('seed-in-rbl-bank', NULL, 'RBL Bank', 'IN', '#21409A', 'R'),
('seed-us-chase', NULL, 'Chase', 'US', '#117ACA', 'C'),
('seed-us-bank-of-america', NULL, 'Bank of America', 'US', '#E31837', 'B'),
('seed-us-wells-fargo', NULL, 'Wells Fargo', 'US', '#D71E28', 'W'),
('seed-us-citi', NULL, 'Citi', 'US', '#056DAE', 'C'),
('seed-us-capital-one', NULL, 'Capital One', 'US', '#004977', 'C'),
('seed-us-american-express', NULL, 'American Express', 'US', '#2E77BB', 'A'),
('seed-us-affirm', NULL, 'Affirm', 'US', '#4A4AF4', 'A'),
('seed-us-klarna', NULL, 'Klarna', 'US', '#FFB3C7', 'K'),
('seed-gb-barclays', NULL, 'Barclays', 'GB', '#00AEEF', 'B'),
('seed-gb-hsbc', NULL, 'HSBC', 'GB', '#DB0011', 'H'),
('seed-gb-lloyds-bank', NULL, 'Lloyds Bank', 'GB', '#006A4D', 'L'),
('seed-gb-natwest', NULL, 'NatWest', 'GB', '#5A287D', 'N'),
('seed-gb-santander', NULL, 'Santander', 'GB', '#EC0000', 'S'),
('seed-ae-emirates-nbd', NULL, 'Emirates NBD', 'AE', '#072B61', 'E'),
('seed-ae-first-abu-dhabi-bank', NULL, 'First Abu Dhabi Bank', 'AE', '#00205B', 'F'),
('seed-ae-mashreq', NULL, 'Mashreq', 'AE', '#F37021', 'M'),
('seed-sg-dbs', NULL, 'DBS', 'SG', '#ED1C24', 'D'),
('seed-sg-ocbc', NULL, 'OCBC', 'SG', '#E2231A', 'O'),
('seed-sg-uob', NULL, 'UOB', 'SG', '#005EB8', 'U'),
('seed-au-commonwealth-bank', NULL, 'Commonwealth Bank', 'AU', '#FFCC00', 'C'),
('seed-au-westpac', NULL, 'Westpac', 'AU', '#DA1710', 'W'),
('seed-au-anz', NULL, 'ANZ', 'AU', '#007DBA', 'A'),
('seed-ca-rbc', NULL, 'RBC', 'CA', '#005DAA', 'R'),
('seed-ca-td-bank', NULL, 'TD Bank', 'CA', '#34A853', 'T'),
('seed-de-deutsche-bank', NULL, 'Deutsche Bank', 'DE', '#0018A8', 'D'),
('seed-jp-mufg', NULL, 'MUFG', 'JP', '#E60012', 'M');
